// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibwzjfukmyjucblirtkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlid3pqZnVrbXlqdWNibGlydGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTc2NTIsImV4cCI6MjA2MjczMzY1Mn0.DV_r1gm767mUaF5rIhzZU3bALpZfDKIH9UHvpXiAF4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);